"""
Implement an OLC assembly algorithm that:

•Takes FASTQ files as input

•Computes all-vs-all read overlaps and constructs an overlap graph,
using the minimum overlap length n as a parameter

•Identifies non-branching paths in the graph

•Generates a layout of reads

•Computes a consensus sequence for each contig

•Outputs contigs as a FASTA file
"""

"""
I used LLM to help me with the code. and testes it with test cases from the class slides, to make sure it works. I also validated the code generated by reading it.

resources used:
https://www.cs.jhu.edu/~langmea/resources/lecture_notes/18_assembly_olc_v2.pdf
"""

import argparse
from collections import defaultdict
from Bio import SeqIO


def read_fastq(file_path: str):
    """
    Read a FASTQ file and extract the sequences.
    
    Args:
        file_path: Path to the FASTQ file
        
    Returns:
        A list of sequences from the FASTQ file
    """
    reads = []
    with open(file_path, 'r') as f:
        for record in SeqIO.parse(f, 'fastq'):
            reads.append(str(record.seq))
    return reads

def main():
    # Set up argument parser
    parser = argparse.ArgumentParser(description='Gets the olc of a given file')
    parser.add_argument('-f', '--file', type=str, required=True,
                      help='Path to input file')
    parser.add_argument('-n', '--minimun-overlap', type=int, required=True, 
                        help='Minimum overlap length')
    parser.add_argument('-o', '--output', type=str, default='contigs.fasta',
                      help='Path to output FASTA file')
    # Parse arguments
    args = parser.parse_args()
    
    # Call the processing function 
    data = read_fastq(args.file)
    
    overlaps_graph = create_overlap_graph(data, args.minimun_overlap)

    non_branching_paths = maximal_non_branching_paths(overlaps_graph)

    layout = layout_reads(non_branching_paths, overlaps_graph)
    
    contigs = generate_contigs(layout)
    
    write_contigs_to_fasta(contigs, args.output)
    print(f"Wrote {len(contigs)} contigs to {args.output}")


def layout_reads(paths, G):
    pos = {}                              # read -> start    
    for path in paths:
        pos.setdefault(path[0], 0)        # seed once
        for a, b in zip(path, path[1:]):  # walk the unitig
            pos.setdefault(b, pos[a] + len(a) - G[a][b])
    return dict(sorted(pos.items(), key=lambda x: x[1]))


def sort_by_in_degree(paths, G):
    """
    Sort paths by in-degree to ensure correct layout.
    
    Args:
        paths: List of paths to sort
        G: Graph representing overlaps
        
    Returns:
        Sorted list of paths
    """
    # Calculate in-degree for each node
    in_degree = {}
    for node in G:
        in_degree[node] = 0
        for neighbor in G[node]:
            in_degree[neighbor] = in_degree.get(neighbor, 0) + 1    
    
    # Sort paths by in-degree
    sorted_paths = sorted(paths, key=lambda path: sum(in_degree[node] for node in path))
    
    return sorted_paths


def maximal_non_branching_paths(graph):
    """
    Find all maximal non-branching paths in a graph.
    
    Args:
        graph: A dictionary where keys are nodes and values are lists of outgoing neighbors
    
    Returns:
        A list of paths, where each path is a list of nodes
    """
    # Calculate in and out degrees
    in_degree = {}
    out_degree = {}
    
    for node in graph:
        out_degree[node] = len(graph[node])
        for neighbor in graph[node]:
            in_degree[neighbor] = in_degree.get(neighbor, 0) + 1
    
    paths = []
    visited_edges = set()
    
    # Find paths starting from non-1-in-1-out nodes
    for v in graph:
        # Check if v is not a 1-in-1-out node and has outgoing edges
        if in_degree.get(v, 0) != 1 or out_degree.get(v, 0) != 1:
            if out_degree.get(v, 0) > 0:
                for w in graph[v]:
                    if (v, w) not in visited_edges:
                        path = [v, w]
                        visited_edges.add((v, w))
                        
                        # Extend path while w is a 1-in-1-out node
                        while w in graph and in_degree.get(w, 0) == 1 and out_degree.get(w, 0) == 1:
                            u = graph[w][0]  # The only outgoing neighbor
                            path.append(u)
                            visited_edges.add((w, u))
                            w = u
                        
                        paths.append(path)
    
    # Find isolated cycles
    for v in graph:
        if in_degree.get(v, 0) == 1 and out_degree.get(v, 0) == 1:
            # Check if this node is part of an unvisited cycle
            w = graph[v][0]
            if (v, w) not in visited_edges:
                cycle = [v]
                current = w
                visited_edges.add((v, w))
                
                # Follow the cycle until returning to starting node
                while current != v:
                    cycle.append(current)
                    if current not in graph or not graph[current]:
                        break  # Not a cycle if a node has no outgoing edges
                    next_node = graph[current][0]
                    visited_edges.add((current, next_node))
                    current = next_node
                
                if current == v:  # Only add if it's a complete cycle
                    paths.append(cycle)
    

    return sort_by_in_degree(paths, graph)


def create_overlap_graph(data: list, minimun_overlap: int):
    # Create a dictionary to store overlaps with their lengths
    overlaps = defaultdict(dict)
    
    # Compare each pair of strings
    for i, s1 in enumerate(data):
        for j, s2 in enumerate(data):
            if i != j:  # Don't compare string with itself
                # Find longest overlap
                max_overlap = 0
                for k in range(min(len(s1), len(s2))):
                    if s1.endswith(s2[:k+1]):
                        max_overlap = k+1
                
                # Store if overlap is at least 1 base
                if max_overlap >= minimun_overlap:
                    overlaps[s1][s2] = max_overlap
    
    return overlaps


def generate_contigs(layout):
    """
    Generate contigs from the layout of reads using majority vote for consensus.
    
    Args:
        layout: Dictionary mapping reads to their starting positions
        
    Returns:
        List of contig sequences
    """
    if not layout:
        return []
    
    # Sort reads by position
    sorted_reads = sorted(layout.items(), key=lambda x: x[1])
    
    # Find the rightmost position
    max_pos = 0
    for read, start in sorted_reads:
        end = start + len(read)
        max_pos = max(max_pos, end)
    
    # Initialize the contig sequence and keep track of bases at each position
    consensus = ['N'] * max_pos
    base_counts = [{} for _ in range(max_pos)]
    
    # Fill in the contig sequence with reads
    for read, start in sorted_reads:
        for i, base in enumerate(read):
            pos = start + i
            if pos < max_pos:
                # Count bases at each position
                if base in base_counts[pos]:
                    base_counts[pos][base] += 1
                else:
                    base_counts[pos][base] = 1
    
    # Determine consensus sequence using majority vote
    for pos in range(max_pos):
        if base_counts[pos]:
            # Find the base with the highest count
            majority_base = max(base_counts[pos].items(), key=lambda x: x[1])[0]
            consensus[pos] = majority_base
    
    # Convert list to string and split by N stretches to get separate contigs
    contig_str = ''.join(consensus)
    # Remove leading and trailing Ns
    contig_str = contig_str.strip('N')
    
    return contig_str.split('N')


def write_contigs_to_fasta(contigs, output_file):
    """
    Write contigs to a FASTA file.
    
    Args:
        contigs: List of contig sequences
        output_file: Path to output FASTA file
    """
    with open(output_file, 'w') as f:
        for i, contig in enumerate(contigs):
            f.write(f">contig{i+1} length={len(contig)}\n")
            # Write sequence with 60 characters per line
            for j in range(0, len(contig), 60):
                f.write(f"{contig[j:j+60]}\n")


if __name__ == "__main__":
    main()
